[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SIBYLS Beamline Documentation"
authors = [{name = "Scott Classen", email = "sclassen@lbl.gov"}]
dynamic = ["version", "description"]
